(()=>{
const V='Art Direction v3';
const DNAs={
 editorial:{name:'EDITORIAL',finish:'soft',bg:'photo',font:'serif',accent:'mono',radius:0,rot:1,space:1.15,grain:.035,desc:'Serif · aire · crops precisos'},
 night:{name:'NIGHT',finish:'punchy',bg:'dark',font:'condensed',accent:'mono',radius:2,rot:2.5,space:.82,grain:.055,desc:'Flash · contraste · crops cerrados'},
 scrapbook:{name:'SCRAPBOOK',finish:'film',bg:'light',font:'rounded',accent:'mono',radius:2,rot:6,space:.9,grain:.065,desc:'Capas · imperfección · memoria'},
 brutal:{name:'BRUTAL',finish:'punchy',bg:'dark',font:'sf',accent:'condensed',radius:0,rot:0,space:.72,grain:.02,desc:'Full bleed · type gigante · tensión'},
 gallery:{name:'GALLERY',finish:'clean',bg:'light',font:'sf',accent:'serif',radius:0,rot:.4,space:1.3,grain:.012,desc:'Museo · margen · silencio'},
 chroma:{name:'CHROMA',finish:'punchy',bg:'photo',font:'display',accent:'sf',radius:1,rot:3,space:.86,grain:.025,desc:'Color extraído · contraste · energía'},
 minimal:{name:'MINIMAL',finish:'clean',bg:'photo',font:'sf',accent:'mono',radius:0,rot:0,space:1.4,grain:0,desc:'Una idea · mucho aire · precisión'},
 kinetic:{name:'KINETIC',finish:'film',bg:'dark',font:'condensed',accent:'display',radius:0,rot:8,space:.78,grain:.04,desc:'Diagonal · movimiento · ritmo'}
};
const keys=Object.keys(DNAs);
S.designDNA=S.designDNA||pick(keys); S.dnaLocked=false;
function dna(){return DNAs[S.designDNA]||DNAs.editorial}
function css(){const s=document.createElement('style');s.textContent=`
#dnaBtn{max-width:150px;overflow:hidden;text-overflow:ellipsis}.dnaCard{margin-top:10px;padding:12px 13px;border:1px solid #2d2d33;border-radius:17px;background:linear-gradient(145deg,#19191d,#0e0e11)}.dnaCard b{font-size:12px;letter-spacing:.12em}.dnaCard small{display:block;margin-top:5px;color:#777;font-size:10px}.slide{transition:background .25s ease}.slide[data-dna="gallery"] .imgLayer{box-shadow:0 14px 34px rgba(0,0,0,.18)}.slide[data-dna="scrapbook"] .imgLayer{box-shadow:0 12px 26px rgba(0,0,0,.25)}.slide[data-dna="night"] .imgLayer{box-shadow:0 16px 42px rgba(0,0,0,.36)}.slide[data-dna="minimal"] .textLayer{letter-spacing:-.035em}.slide[data-dna="brutal"] .textLayer{letter-spacing:-.075em}.slide[data-dna="editorial"] .textLayer{letter-spacing:-.045em}.premiumGrain{position:absolute;inset:0;pointer-events:none;z-index:199;opacity:.15;mix-blend-mode:soft-light;background-image:url("data:image/svg+xml,%3Csvg viewBox='0 0 180 180' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.9' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='.35'/%3E%3C/svg%3E")}`;document.head.appendChild(s)}css();
const bar=$('#controlBar');
const dnaBtn=document.createElement('button');dnaBtn.id='dnaBtn';dnaBtn.className='pill wow';bar?.appendChild(dnaBtn);
const varBtn=document.createElement('button');varBtn.id='variationBtn';varBtn.className='pill';varBtn.textContent='≈ Variación';bar?.appendChild(varBtn);
const remixBtn=document.createElement('button');remixBtn.id='remixAllBtn';remixBtn.className='pill';remixBtn.textContent='✦ Remix';bar?.appendChild(remixBtn);
const sheet=document.createElement('div');sheet.className='sheet';sheet.id='dnaSheet';sheet.innerHTML='<div class="grab"></div><div class="sheetTop"><b>Design DNA</b><button class="done" id="dnaDone">Listo</button></div><div class="row" id="dnaRow"></div><div class="dnaCard" id="dnaCard"></div><div class="grid2"><button id="dnaLock">Bloquear dirección</button><button id="dnaApply">Aplicar de nuevo</button></div><small class="note">El DNA gobierna crops, ritmo, tipografía, color, rotación y acabado. Random sigue variando, pero dentro de una dirección coherente.</small>';document.body.appendChild(sheet);
function showDNA(){const d=dna();dnaBtn.textContent='DNA · '+d.name;$('#dnaRow').innerHTML=keys.map(k=>`<button class="choice ${k===S.designDNA?'on':''}" data-dna="${k}">${DNAs[k].name}</button>`).join('');$('#dnaCard').innerHTML=`<b>${d.name}</b><small>${d.desc}</small>`;$('#dnaLock').textContent=S.dnaLocked?'Desbloquear dirección':'Bloquear dirección'}
function bgFor(sl,d){const p=sl.palette||[];if(d.bg==='dark')return '#0b0b0d';if(d.bg==='light')return '#f1efe9';return sl.bg}
function textInk(sl,d){if(d.bg==='dark')return '#f7f5f1';if(d.bg==='light')return '#111113';const p=sl.palette?.[0];return p?contrastText(p):'#fff'}
function addEditorialMarks(sl,d,i){sl.layers=sl.layers.filter(l=>!l.dnaDeco);const ink=textInk(sl,d);if(['editorial','gallery','minimal'].includes(S.designDNA)){const a=makeDeco('line',18,18,ri(34,92),2,ink,0);a.dnaDeco=true;a.z=22;sl.layers.push(a)}if(S.designDNA==='brutal'){const a=makeDeco('block',ri(-8,220),ri(20,360),ri(70,145),ri(8,18),rgbToCss(pick(sl.palette?.slice(2)||[[255,45,90]])),0);a.dnaDeco=true;a.z=18;sl.layers.push(a)}if(S.designDNA==='kinetic'){const a=makeDeco('line',-20,ri(80,340),390,3,ink,rnd(-12,12));a.dnaDeco=true;a.z=21;sl.layers.push(a)}if(S.designDNA==='scrapbook'&&Math.random()<.75){const a=makeDeco('block',ri(12,260),ri(20,370),ri(42,90),ri(12,28),'rgba(245,235,200,.78)',rnd(-9,9));a.dnaDeco=true;a.z=32;sl.layers.push(a)}}
function artDirect(sl,i,soft=false){const d=dna(),ink=textInk(sl,d);sl.dna=S.designDNA;sl.bg=bgFor(sl,d);S.finish=d.finish;const imgs=sl.layers.filter(l=>l.type==='img'),texts=sl.layers.filter(l=>l.type==='text');imgs.forEach((l,j)=>{if(l.locked)return;l.rot=Math.max(-d.rot,Math.min(d.rot,l.rot));if(S.designDNA==='gallery'){l.x=Math.max(22,l.x);l.y=Math.max(28,l.y);l.w=Math.min(l.w,296);l.h=Math.min(l.h,360)}if(S.designDNA==='minimal'&&j>0)l.hidden=true;if(S.designDNA==='night'){l.zoom=Math.max(1.08,l.zoom);l.offX*=.7;l.offY*=.7}if(S.designDNA==='brutal'&&j===0){l.x=Math.min(0,l.x);l.y=Math.min(0,l.y);l.w=Math.max(340,l.w);l.h=Math.max(425,l.h);l.rot=0}if(S.designDNA==='scrapbook'){l.rot=Math.max(-6,Math.min(6,l.rot||rnd(-5,5)));l.w*=.92;l.h*=.92;l.x+=rnd(-6,8);l.y+=rnd(-6,8)}if(S.designDNA==='kinetic')l.rot=Math.max(-8,Math.min(8,(j%2?1:-1)*rnd(2,7)));});texts.forEach((t,j)=>{if(t.locked)return;t.color=j===0?ink:(sl.palette?.[2]?rgbToCss(sl.palette[2]):ink);t.font=j===0?d.font:d.accent;t.rot=Math.max(-d.rot,Math.min(d.rot,t.rot));if(j===0){if(S.designDNA==='brutal'){t.size=Math.max(56,t.size);t.w=Math.max(260,t.w);t.x=rnd(-8,22)}else if(S.designDNA==='editorial'){t.size=Math.max(36,Math.min(68,t.size));t.weight=pick([400,700]);}else if(S.designDNA==='gallery'){t.size=Math.min(42,t.size);t.weight=400;t.x=Math.max(24,t.x)}else if(S.designDNA==='minimal'){t.size=Math.min(36,t.size);t.weight=pick([400,700])}else if(S.designDNA==='night'){t.size=Math.max(42,t.size);t.weight=900}else if(S.designDNA==='kinetic'){t.size=Math.max(44,t.size);t.weight=900;t.rot=rnd(-7,7)}}else{t.size=Math.min(t.size,24);t.weight=pick([400,700])}});addEditorialMarks(sl,d,i)}
function applyDNA(){S.slides.forEach((sl,i)=>artDirect(sl,i));showDNA()}
const prevBuild=buildSlides;buildSlides=function(){if(!S.dnaLocked)S.designDNA=pick(keys);prevBuild();applyDNA()};
const prevRenderStage=renderStage;renderStage=function(){prevRenderStage();$$('.slide').forEach((el,i)=>{el.dataset.dna=S.slides[i]?.dna||S.designDNA;const g=document.createElement('div');g.className='premiumGrain';g.style.opacity=String((dna().grain||0)*3);el.appendChild(g);$$('.imgLayer',el).forEach(img=>{img.style.borderRadius=dna().radius?`${dna().radius*6}px`:'0'})});showDNA()};
function variation(){pushHistory();S.slides.forEach((sl,i)=>{sl.layers.forEach(l=>{if(l.locked)return;if(l.type==='img'){l.x+=rnd(-10,10);l.y+=rnd(-10,10);l.w*=rnd(.94,1.06);l.h*=rnd(.94,1.06);l.zoom=Math.max(1,Math.min(2.2,l.zoom+rnd(-.05,.08)));l.offX=Math.max(-40,Math.min(40,l.offX+rnd(-6,6)));l.offY=Math.max(-40,Math.min(40,l.offY+rnd(-6,6)))}if(l.type==='text'){l.x+=rnd(-12,12);l.y+=rnd(-14,14);l.size*=rnd(.92,1.08)}});artDirect(sl,i,true)});renderAll();toast('Variación · mismo DNA')}
function remix(){pushHistory();S.designDNA=pick(keys.filter(k=>k!==S.designDNA));const lock=S.dnaLocked;S.dnaLocked=true;prevBuild();S.dnaLocked=lock;applyDNA();renderAll();toast('Nueva dirección · '+dna().name)}
dnaBtn.onclick=()=>{showDNA();closeSheets();$('#dnaSheet').classList.add('on')};$('#dnaDone').onclick=()=>$('#dnaSheet').classList.remove('on');$('#dnaRow').onclick=e=>{const b=e.target.closest('[data-dna]');if(!b)return;pushHistory();S.designDNA=b.dataset.dna;applyDNA();renderAll();showDNA();toast(DNAs[S.designDNA].name)};$('#dnaLock').onclick=()=>{S.dnaLocked=!S.dnaLocked;showDNA();saveProject();toast(S.dnaLocked?'DNA bloqueado':'DNA libre')};$('#dnaApply').onclick=()=>{pushHistory();applyDNA();renderAll();toast('Dirección aplicada')};varBtn.onclick=variation;remixBtn.onclick=remix;
const oldRandom=$('#randomBtn').onclick;$('#randomBtn').onclick=()=>{if(S.dnaLocked){const old=S.designDNA;oldRandom?.();S.designDNA=old;applyDNA();renderAll();toast('Random dentro de '+dna().name)}else oldRandom?.()};
const oldRenderAll=renderAll;renderAll=function(){oldRenderAll();showDNA();const m=$('#modeLabel');if(m)m.textContent=`${dna().name} · ${S.finish}`};
showDNA();applyDNA();renderAll();toast('Design DNA listo');
})();